### ISSUE TITLE
open class support

### ISSUE THREAD

**Issue by rubydesign** [rubys/ruby2js#22] opened 2018-02-13 13:31 UTC
So i moved on to 3d programming, and the libraries are huge (>1mb) meaning load times go over 10s.

To live with that i spent a day to get hot reloading working (ie changed files are compiled and pushed to the browser, and the client calls a user-defined function to redraw). This works well without the es2016. Sub-second refreshes, happy Torsten.

But when i switch es2015 on, the pushed code redefines a class, and for some strange reason js folks have chosen not to allow that. (having in effect closed classes in such a dynamic language, strange).

Now i know this is not ruby2js related, i was just hoping you might have a solution. Or something can be done in the conversion (some switch?).

**Comment by rubys** [comment] 2018-02-13 17:25
Classes are not closed in JavaScript, but the syntax for adding a property/method/whatever is different than the syntax one would use for the initial definition.  With Ruby, there is no difference.

Starting with:

```ruby
class Frame
  def a()
    console.log 'a'
  end
end

class Frame
  def b()
    console.log 'b'
  end
end

Frame.new().a()
```

The code produced (without es2015) would be:

```javascript
function Frame() {};

Frame.prototype.a = function() {
  console.log("a")
};

function Frame() {};

Frame.prototype.b = function() {
  console.log("b")
};

new Frame().a()
```

Other than redefining the constructor for the Frame class, this code will work as intended.

Now with es2015 support turned on, the output looks like:

```javascript
class Frame {
  a() {
    console.log("a")
  }
};

class Frame {
  b() {
    console.log("b")
  }
};

new Frame().a()
```

This does result in a SyntaxError as Frame has already been declared, but note that the following javascript works:

```javascript
class Frame {
  a() {
    console.log("a")
  }
};

Frame.prototype.b = function() {
  console.log("b")
};

new Frame().a()
```

Now what we would need is a way to provide a hint that a given class definition is meant to reopen and extend an existing class.  Ideally, that would be pure Ruby.  Second best would be something that mimics JavaScript semantics.  At a minimum, it would need to be syntactically correct Ruby; and if neither of the first two preferences are met, it would be something that is both eye catching and ideally provides a hint as to what the function would be.

With Ruby, all unary operators are available in this context, so something like the following would be possible:

```ruby
++class Frame
end
```

It is syntactically correct Ruby, not something one is likely to encounter in the wild, and perhaps even gives a bit of a hint that you are extending a class.  If you like this suggestion (or have a different suggestion), I can take a look at the code.  Mostly it would mean turning off es2015 support for that one class definition, as well as turning off things like creation of default constructors when they are not present.

**Comment by rubydesign** [comment] 2018-02-14 13:18
Wow, thanks for that explicit explanation. 
I had almost understood that before, maybe my wording was bad: i meant the closed in relation to es2015 own syntax. I know you can fallback, though there was something about the meaning of this changing that i didn't get.

Your suggestion sounds fine to me. Ideally i was first thinking a compiler switch, but i don't think i can get that through to the place it's needed.

Your suggestion is good in the sense that one can just add those ++ for the file one is working on and otherwise keep the code clean es2015. 
If you could have a look at that that would be great.
(But don't break your back about it, i just found a smaller tool, and with tree-shaking, that might go to less than 100k)
Thanks

**Closed** 2018-02-14 16:45 UTC

**Comment by rubydesign** [comment] 2018-02-15 01:32
Very cool, thanks.
Just read the code now, but will try later.

**Comment by rubydesign** [comment] 2018-02-16 15:23
Now i've tried it and it works as planned. 
But the plan has a small glitch: when i debug with the ++  the hotload works. but a reload does not.
So then i have to toggle the ++ all the time. Not just before check-in as planned.

This is what i get for a constructor with `++class PostBeam` 
```
[(PostBeam = function PostBeam(app, index, offset) {
  this._size = 15;
}).prototype] = [PostBeam.prototype];
```
It complains about PostBeam not being defined, on the last line.

**Comment by rubys** [comment] 2018-02-16 16:27
You should be able to work around it by adding the following before the class (re)definition:

```
def PostBeam; end unless defined? PostBeam
```

If this works for you, this code could be either automatically emitted whenever `++class` is encountered; or we could have another prefix defined for conditional extensions.  I guess I lean towards not adding a different prefix.  Thoughts?

---

As an aside, classes in JavaScripts are constructors with a prototype property.  Therefore, one does not simply replace a constructor, instead one defines a new constructor, and copies the prototype property.  The extra [] uses a destructuring assignment ensuring that the order of evaluation is righthand side before the lefthand side.

**Comment by rubydesign** [comment] 2018-02-17 04:06
Ok, that works. If i put the `def..` there when i need the ++, the hotload works and also reaload works.
It does not work with the class (no ++) syntax, but like you say, if it is emitted automatically with ++ constructor this all works great.

The aside is clever stuff.
